### ISSUE TITLE
WindowsAuthenticator will no longer work in certain scenarios under .Net 5.0

### ISSUE THREAD

**Issue by robertcoltheart** [jonnii/SpeakEasy#112]
Under the covers, HttpClient uses a new protocol, and in our testing, using Windows authentication will usually result in an `Unauthorized` error. See https://docs.microsoft.com/en-US/dotnet/core/run-time-config/networking

In .Net 3.x, you could work around this by forcing HttpClient to use the old stack, using:

```c#
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
```

However in .Net 5.0 this setting is no longer available. Instead, you'd need to use the https://www.nuget.org/packages/System.Net.Http.WinHttpHandler package and use that handler. Trouble is, this is a Windows-only thing, and adding this as a dependency in SpeakEasy will make it non-cross platform.

I thought of adding a `DefaultClientHandler` property to `HttpClientSettings`. Trouble is that all the `IAuthenticator` implementations use `HttpClientSettings` in their signatures, and we'd have change it to be `HttpMessageHandler`, which is a significant breaking change. Furthermore, the `WindowsAuthenticator` wouldn't work with that implementation either, given that the handler can either be a `HttpClientHandler` or a `WinHttpHandler`, both of which use different properties to set the credentials.

Conundrum.

**Comment by jonnii** [comment]
There's no easy to solve this one unfortunately - I think your inclination to use an `HttpMessageHandler` makes the most sense, even though that's a breaking change it seems that's the way everything is going. I would suggest pulling out the windows auth and making it a user space issue, someone can provide their own handler and cast however they need to.
