### ISSUE TITLE
Can we add support for writing dictionaries as query string parameters

### ISSUE THREAD

**Issue by tm011064** [jonnii/SpeakEasy#93]
Hi @jonnii , it would be good to support dictionary like query string parameters, something like this:

``` c#
var fields = new Dictionary<object, object>()
{
  { "foo": "foo-values" },
  { "bar": "bar-values" }
}

httpClient.Get("authors", new { fields })
// -> translates to "GET ...authors?fields[foo]=foo-values&fields[bar]=bar-values"
```

The `ApiController` accepts such query string parameters natively (`[FromQuery] Dictionary<string, string> fields`), it would be great if speakeasy would support creating the parameters from a dictionary also

**Comment by robertcoltheart** [comment]
That's quite a `json:api` specific interpretation of dictionary query string parameters. Perhaps what we need is something like an `IDictionaryFormatter` on the `HttpClientSettings` so that you could specify a custom parameter strategy?

**Comment by jonnii** [comment]
So you _can_ do this today (i think) by implementing a middleware which wraps the `IHttpRequest` and then having a special case implementation which overrides:

`
 /// <summary>
        /// Builds the method specific request url
        /// </summary>
        /// <returns>A url</returns>
        string BuildRequestUrl(IArrayFormatter arrayFormatter);
`

That said, I think this is a narrow and specific enough use case that something like @robertcoltheart is suggesting makes perfect sense. Ideally I'd still like to package this up as a middleware (as i like that pattern for extensibility) but I'd need to think about the best way to do that.
